### ISSUE TITLE
CallbackURL

### ISSUE THREAD

**Issue by nissrinel** [mehdirochdi/cmi-payment-php#2]
Hello,
I'm working with cmi api in a react and node js project.
My problem is with callback URL, in the Integration kit they mentioned that it should be accessible through internet with specific port 80 443 but I didn't deploy my website yet. And when I redirect the callback request to my local file it doesn't work.

Below the screen of the error page 
![capt](https://user-images.githubusercontent.com/58444926/128170536-5f619413-e4a2-40ca-8e92-b69a54ab94a3.jpg)

**Comment by mehdirochdi** [comment]
Hello, to be honest, I didn't set any port it should be working locally or on production, are you specified the right callback link, just look at my class.

**Comment by nissrinel** [comment]
**Problem solved** Thank you sir, It was with the Callback URL, By changing the URL with a public address from the proxy Ngrok https://ngrok.com/, the request has been done successfully !

**Comment by mehdirochdi** [comment]
Good to know
